#!/usr/bin/bash

modules=(
Proc::ProcessTable
DB
Linux::Inotify2
Moose 
DBI
DBD::mysql.pm
Clone
Tk
Tk::ToolBar
)

for module in "${modules[@]}"
do
    perldoc $module &> /dev/null
    if [ $? -ne 1 ]
    then
       echo >&2 "Module $module already installed. Skipping" 
    else
       cpanp i "$module"
    fi
done
